node {
  def project = 'weather-2017'
  def appName = 'gceme'
  def feSvcName = "${appName}-frontend"
  def imageTag = "gcr.io/${project}/${appName}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"
  def dockerTag ="${env.BUILD_NUMBER}"

  checkout scm

  stage 'Build image'
  sh("docker build -t ${imageTag} .")

  stage 'Run Go tests'
  sh("docker run ${imageTag} go test")

  stage 'check'
  sh("whoami")

  /***stage 'Push image to registry'
  sh("gcloud docker -- push ${imageTag}")**/

  stage 'Docker push'
  docker.build('benmorris/hellonode9')
  docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
    docker.image('benmorris/hellonode9').push('latest')

    slackSend color: 'RED', message: 'Hello'
    slackSend (color: '#FFFF00', message: "STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
    sh "docker images"
  }
